title: "BPEd 3201 Project"
description: "An educational website about drugs of abuse with videos and quizzes."
baseurl: "" # Leave this empty if deploying to https://username.github.io
url: "https://your-username.github.io" # Replace with your GitHub Pages URL

# Optional GitHub Pages settings
theme: minima

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation (optional if using your own layout)
nav:
  - title: "Home"
    url: "/"
